// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGBHK3HRTheonYd8rSig6LdlGeVMmqiJQ',
    appId: '1:756491342369:web:f6fff0bc1318de51500960',
    messagingSenderId: '756491342369',
    projectId: 'diafootcare-95912',
    authDomain: 'diafootcare-95912.firebaseapp.com',
    storageBucket: 'diafootcare-95912.firebasestorage.app',
    measurementId: 'G-7Y9765B0XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt30OTdnAy5Yeu7ttDSo6_LRCnyKZh4O0',
    appId: '1:756491342369:android:23b1c300fdc8ea45500960',
    messagingSenderId: '756491342369',
    projectId: 'diafootcare-95912',
    storageBucket: 'diafootcare-95912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dP3tpEr7bGjO6Ed3fhuNCe96cXdHvNQ',
    appId: '1:756491342369:ios:6beb6c199d696e46500960',
    messagingSenderId: '756491342369',
    projectId: 'diafootcare-95912',
    storageBucket: 'diafootcare-95912.firebasestorage.app',
    iosBundleId: 'com.example.diafootCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dP3tpEr7bGjO6Ed3fhuNCe96cXdHvNQ',
    appId: '1:756491342369:ios:6beb6c199d696e46500960',
    messagingSenderId: '756491342369',
    projectId: 'diafootcare-95912',
    storageBucket: 'diafootcare-95912.firebasestorage.app',
    iosBundleId: 'com.example.diafootCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGBHK3HRTheonYd8rSig6LdlGeVMmqiJQ',
    appId: '1:756491342369:web:71434669315a8634500960',
    messagingSenderId: '756491342369',
    projectId: 'diafootcare-95912',
    authDomain: 'diafootcare-95912.firebaseapp.com',
    storageBucket: 'diafootcare-95912.firebasestorage.app',
    measurementId: 'G-HZ559ZRKQL',
  );
}
